language: generic
sudo: required
services:
  - docker

after_success:
  - docker build -t narasimhakamath/fithub-api-gateway ./api-gateway
  - docker build -t narasimhakamath/fithub-users-service ./users-service

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push narasimhakamath/fithub-api-gateway
  - docker push narasimhakamath/fithub-users-service