version: '3'
services:
  api-gateway:
    build:
      dockerfile: Dockerfile.dev
      context: ./api-gateway
    volumes:
      - /home/node/app/node_modules
      - ./api-gateway:/home/node/app
    ports:
      - "3000:3000"