version: '3'
services:
  user-mongo:
    image: mongo:latest
    ports:
      - "4017:27017"
    logging:
      driver: "none"
  api-gateway:
    build:
      dockerfile: Dockerfile.dev
      context: ./api-gateway
    volumes:
      - /home/node/app/node_modules
      - ./api-gateway:/home/node/app
    ports:
      - "3000:3000"
  users-service:
    build:
      dockerfile: Dockerfile.dev
      context: ./users-service
    volumes:
      - /home/node/app/node_modules
      - ./users-service:/home/node/app
    ports:
      - "4000:4000"
    depends_on:
      - user-mongo